# -*- coding: utf-8 -*-
"""OD_Skill.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sxnDzkPX6h2_ejMH1LW6Xqd6wcHvdM5G
"""

!pip install torch torchvision pandas opencv-python matplotlib

pip install kaggle

!pip install -q kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle competitions download -c rsna-pneumonia-detection-challenge

!unzip "*.zip"

!wget https://github.com/ieee8023/covid-chestxray-dataset/archive/refs/heads/master.zip

!unzip master.zip

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

path = "covid-chestxray-dataset-master/images"

data = []
labels = []

for img_name in os.listdir(path):

    img_path = os.path.join(path, img_name)

    img = cv2.imread(img_path)
    img = cv2.resize(img,(128,128))

    data.append(img)

    if "covid" in img_name.lower():
        labels.append(1)
    else:
        labels.append(0)

data = np.array(data)/255.0
labels = np.array(labels)

labels = to_categorical(labels,2)

print("Dataset shape:",data.shape)

X_train,X_test,y_train,y_test = train_test_split(
    data,labels,test_size=0.2,random_state=42
)

model = Sequential()

model.add(Conv2D(32,(3,3),activation='relu',input_shape=(128,128,3)))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Flatten())

model.add(Dense(128,activation='relu'))
model.add(Dense(2,activation='softmax'))

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    X_train,
    y_train,
    epochs=5,
    validation_data=(X_test,y_test)
)

loss,accuracy = model.evaluate(X_test,y_test)

print("Test Accuracy:",accuracy)
model.save("covid_model.h5")

img = X_test[0]

prediction = model.predict(np.expand_dims(img,axis=0))

label = np.argmax(prediction)

plt.imshow(img)
plt.title("COVID Detected" if label==1 else "Normal")
plt.axis("off")

img = (img*255).astype("uint8")

h,w,_ = img.shape

start = (int(w*0.3),int(h*0.3))
end = (int(w*0.7),int(h*0.7))

cv2.rectangle(img,start,end,(0,255,0),2)

plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
plt.title("Detected Region")
plt.axis("off")